const express = require("express");
const cors = require('cors');
// const coursesRoutes = require("./routes/courses.routes");

const db = require("./config/db");
const app = express();
app.use(cors())

const bodyParser = require("body-parser");
const appRoute = require("./routes/app.route")
const course=require("./routes/course.routes")
const customer=require("./routes/customer.route")
const admin=require("./routes/admin.route")
const SuperAdmin=require("./routes/SuperAdmin.route")
const user=require("./routes/user.route")
const lession=require("./routes/lession.route")
const Coupons=require("./routes/Coupons.route")
const cartRout=require("./routes/cart.route")
const Bag=require("./routes/Bag.route")
const wishlist=require("./routes/wishlist.route")
const userGroup=require("./routes/userGroup.route")
const group=require("./routes/group.route")
const role=require("./routes/role.route")
const assignment=require("./routes/assignment.route")
const student=require("./routes/student.route")
const manager=require("./routes/manager.route")
const groupApp=require("./routes/groupApp.route")
const userApp=require("./routes/userApp.route")
const brand=require("./routes/brand.route")
const product=require("./routes/product.route")
const personalDetails=require("./routes/personalDetails.route")
const familyInfo=require("./routes/familyInfo.route")
const hostel=require("./routes/hostel.route")
const fees=require("./routes/fees.route")
const feesdata=require("./routes/feesdata.route")
const login=require("./routes/login.route");
const registration = require("./routes/registration.route")
const supplier = require("./routes/supplier.route");
const request=require("./routes/request.route")
const offer=require("./routes/offer.route")
const order=require("./routes/order.route")
const categories=require("./routes/categories.route")
const subcategories=require("./routes/subcategories.route")
const booking=require("./routes/booking.route")
const stores=require("./routes/stores.route")
const technicians=require("./routes/technicians.route")
const market=require("./routes/market.route");
const shipping = require("./routes/shipping.route");
const list=require("./routes/list.route")
const canteen=require("./routes/canteen.route")
const leave=require("./routes/leave.route")
const attendance=require("./routes/attendance.route")
const post=require("./routes/post.route")
const vehicals=require("./routes/vehicals.route")
const peopledata=require("./routes/peopledata.route");
const agents = require("./routes/agents.route");
const permission= require("./routes/permission.route");
const address=require("./routes/address.route")
const useraddress=require("./routes/useraddress.route")
const apollo=require("./routes/apollo.route")
const astron=require("./routes/astron.route")
const pheonix=require("./routes/pheonix.route")
const severe=require("./routes/severe.route")
const random=require("./routes/random.route")
const bongo=require("./routes/bongo.route")
const test=require("./routes/test.route")
const formula=require("./routes/formula.route")
const define=require("./routes/define.route")
const object=require("./routes/object.route")
const next=require("./routes/next.route")
const result =require("./routes/result.route")
const folder=require("./routes/folder.route")
const create=require("./routes/create.route")
const developer=require("./routes/developer.route")
const code=require("./routes/code.route")
const window=require("./routes/window.route")
const content=require("./routes/content.route")
const editor=require("./routes/editor.route")
const shortcut=require("./routes/shortcut.route")
const control=require("./routes/control.route")
const keyword=require("./routes/keyword.route")


// support parsing of application/json type post data
app.use(bodyParser.json());

//support parsing of application/x-www-form-urlencoded post data
app.use(bodyParser.urlencoded({ extended: true }));

app.get("/", (req, res) => {
  res.send("Hello everyone!");
});
app.use("/app",appRoute)
app.use("/course",course)
app.use("/customer",customer)
app.use("/admin",admin)
app.use("/SuperAdmin",SuperAdmin)
app.use("/user",user)
app.use("/lession",lession)
app.use("/Coupons",Coupons)
app.use("/cart",cartRout)
app.use("/Bag",Bag)
app.use("/wishlist",wishlist)
app.use("/userGroup",userGroup)
app.use("/group",group)
app.use("/role",role)
app.use("/assignment",assignment)
app.use("/student",student)
app.use("/manager",manager)
app.use("/groupApp",groupApp)
app.use("/userApp",userApp)
app.use("/brand",brand)
app.use("/product",product)
app.use("/personalDetails",personalDetails)
app.use("/familyInfo",familyInfo)
app.use("/hostel",hostel)
app.use("/fees",fees)
app.use("/feesdata",feesdata)
app.use("/login",login)
app.use("/registration",registration)
app.use("/supplier",supplier)
app.use("/request",request)
app.use("/offer",offer)
app.use("/order",order)
app.use("/categories",categories)
app.use("/subcategories",subcategories)
app.use("/booking",booking)
app.use("/stores",stores)
app.use("/technicians",technicians)
app.use("/market",market)
app.use("/shipping",shipping)
app.use("/list",list)
app.use("/canteen",canteen)
app.use("/leave",leave)
app.use("/attendance",attendance)
app.use("/post",post)
app.use("/vehicals",vehicals)
app.use("/peopledata",peopledata)
app.use("/agents",agents)
app.use("/permission",permission)
app.use("/address",address)
app.use("/useraddress",useraddress)
app.use("/apollo",apollo)
app.use("/astron",astron)
app.use("/pheonix",pheonix)
app.use("/severe",severe)
app.use("/random",random)
app.use("/bongo",bongo)
app.use("/test",test)
app.use("/formula",formula)
app.use("/define",define)
app.use("/object",object)
app.use("/next",next)
app.use("/result",result)
app.use("/folder",folder)
app.use("/create",create)
app.use("/developer",developer)
app.use("/code",code)
app.use("/window",window)
app.use("/content",content)
app.use("/developer",developer)
app.use("/editor",editor)
app.use("/shortcut",shortcut)
app.use("/control",control)
app.use("/keyword",keyword)

// app.use("/course", coursesRoutes);

// app.listen(port, () => {
//   console.log(`Example app listening on port ${port}`)
// })

module.exports = app;
